import 'dotenv/config';
import { Client } from 'pg';

const client = new Client({ connectionString: process.env.DATABASE_URL });

const cards = [
{"name":"The Fool","number":0,"arcana":"major","suit":null,"image":"/images/cards/the-fool.jpg","description":"Một chàng trai trẻ bước đi đầy tự tin tới mép vực, biểu tượng của sự khởi đầu mới và lòng tin ngây thơ.","detailed_meaning":"The Fool đại diện cho những bước đi đầu tiên của hành trình.","upright":["Khởi đầu mới","Sự ngây thơ","Tự phát","Niềm tin","Tự do"],"reversed":["Bất cẩn","Thiếu suy nghĩ","Rủi ro","Ngây thơ thái quá"],"keywords":["Beginnings","Faith","Freedom"],"element":"Air","zodiac":"Uranus","yes_no":"yes","slug":"the-fool"},
{"name":"The Magician","number":1,"arcana":"major","suit":null,"image":"/images/cards/the-magician.jpg","description":"Một tay chỉ lên trời, một tay chỉ xuống đất.","detailed_meaning":"Khả năng biến ý tưởng thành hiện thực.","upright":["Sức mạnh ý chí","Sáng tạo","Hành động","Tài năng"],"reversed":["Thao túng","Kế hoạch kém","Tài năng bị bỏ phí"],"keywords":["Power","Action","Resourcefulness"],"element":"Air","zodiac":"Mercury","yes_no":"yes","slug":"the-magician"},
{"name":"The High Priestess","number":2,"arcana":"major","suit":null,"image":"/images/cards/the-high-priestess.jpg","description":"Ngồi giữa hai cột đen trắng, giữ bí mật của tiềm thức.","detailed_meaning":"Lắng nghe trực giác.","upright":["Trực giác","Bí ẩn","Tiềm thức","Sự im lặng"],"reversed":["Mất kết nối nội tâm","Bí mật bị lộ","Sự hời hợt"],"keywords":["Intuition","Mystery","Unconscious"],"element":"Water","zodiac":"Moon","yes_no":"maybe","slug":"the-high-priestess"},
{"name":"The Empress","number":3,"arcana":"major","suit":null,"image":"/images/cards/the-empress.jpg","description":"Người phụ nữ quyền năng giữa thiên nhiên trù phú.","detailed_meaning":"Tính nữ, sáng tạo và nuôi dưỡng.","upright":["Sinh sôi","Nuôi dưỡng","Thiên nhiên","Sáng tạo"],"reversed":["Thiếu sáng tạo","Sự phụ thuộc","Sự bỏ bê"],"keywords":["Abundance","Nature","Fertility"],"element":"Earth","zodiac":"Venus","yes_no":"yes","slug":"the-empress"},
{"name":"The Emperor","number":4,"arcana":"major","suit":null,"image":"/images/cards/the-emperor.jpg","description":"Người đàn ông nghiêm nghị trên ngai vàng đá.","detailed_meaning":"Sự bảo vệ, quyền lực và trật tự.","upright":["Quyền lực","Cấu trúc","Kỷ luật","Sự bảo vệ"],"reversed":["Độc đoán","Thiếu linh hoạt","Kiểm soát quá mức"],"keywords":["Authority","Structure","Control"],"element":"Fire","zodiac":"Aries","yes_no":"yes","slug":"the-emperor"},
{"name":"The Hierophant","number":5,"arcana":"major","suit":null,"image":"/images/cards/the-hierophant.jpg","description":"Vị giáo sĩ giữa hai cột trụ.","detailed_meaning":"Giá trị truyền thống và sự dẫn dắt.","upright":["Truyền thống","Sự phù hợp","Niềm tin","Giáo dục","Cố vấn"],"reversed":["Nổi loạn","Tự do cá nhân","Phá vỡ quy chuẩn"],"keywords":["Tradition","Conformity","Morality"],"element":"Earth","zodiac":"Taurus","yes_no":"maybe","slug":"the-hierophant"},
{"name":"The Lovers","number":6,"arcana":"major","suit":null,"image":"/images/cards/the-lovers.jpg","description":"Hai nhân vật dưới sự bảo hộ của thiên thần.","detailed_meaning":"Sự lựa chọn và kết nối tâm giao.","upright":["Tình yêu","Sự hòa hợp","Lựa chọn","Kết nối","Giá trị"],"reversed":["Mất cân bằng","Lựa chọn sai","Xung đột nội tâm"],"keywords":["Love","Alignment","Choices"],"element":"Air","zodiac":"Gemini","yes_no":"yes","slug":"the-lovers"},
{"name":"The Chariot","number":7,"arcana":"major","suit":null,"image":"/images/cards/the-chariot.jpg","description":"Chiến binh điều khiển hai con nhân sư.","detailed_meaning":"Kiểm soát, kỷ luật và quyết tâm.","upright":["Chiến thắng","Kỷ luật","Quyết tâm","Hành động","Tự chủ"],"reversed":["Mất kiểm soát","Thiếu định hướng","Hung hăng"],"keywords":["Direction","Control","Willpower"],"element":"Water","zodiac":"Cancer","yes_no":"yes","slug":"the-chariot"},
{"name":"Strength","number":8,"arcana":"major","suit":null,"image":"/images/cards/strength.jpg","description":"Người phụ nữ nhẹ nhàng chế ngự con sư tử.","detailed_meaning":"Sức mạnh từ kiên nhẫn và lòng trắc ẩn.","upright":["Can đảm","Kiên nhẫn","Lòng trắc ẩn","Kiểm soát bản năng"],"reversed":["Tự ti","Nỗi sợ","Yếu đuối"],"keywords":["Courage","Influence","Compassion"],"element":"Fire","zodiac":"Leo","yes_no":"yes","slug":"strength"},
{"name":"The Hermit","number":9,"arcana":"major","suit":null,"image":"/images/cards/the-hermit.jpg","description":"Cụ già cầm đèn soi rọi bóng tối.","detailed_meaning":"Tìm chân lý trong cô độc.","upright":["Cô độc","Tìm kiếm chân lý","Nội tâm","Sự dẫn dắt"],"reversed":["Cô lập","Kẻ lập dị","Rút lui quá mức"],"keywords":["Solitude","Guidance","Introspection"],"element":"Earth","zodiac":"Virgo","yes_no":"maybe","slug":"the-hermit"},
{"name":"Wheel of Fortune","number":10,"arcana":"major","suit":null,"image":"/images/cards/wheel-of-fortune.jpg","description":"Bánh xe xoay tròn với biểu tượng thần bí.","detailed_meaning":"Không có gì là vĩnh viễn.","upright":["May mắn","Thay đổi","Định mệnh","Điểm mấu chốt"],"reversed":["Vận đen","Kháng cự thay đổi","Chu kỳ lặp lại"],"keywords":["Change","Cycles","Destiny"],"element":"Fire","zodiac":"Jupiter","yes_no":"yes","slug":"wheel-of-fortune"},
{"name":"Justice","number":11,"arcana":"major","suit":null,"image":"/images/cards/justice.jpg","description":"Cầm cân và kiếm.","detailed_meaning":"Mọi hành động đều có phản ứng tương xứng.","upright":["Công lý","Sự thật","Nhân quả","Trách nhiệm"],"reversed":["Bất công","Thiếu trách nhiệm","Gian lận"],"keywords":["Fairness","Truth","Law"],"element":"Air","zodiac":"Libra","yes_no":"maybe","slug":"justice"},
{"name":"The Hanged Man","number":12,"arcana":"major","suit":null,"image":"/images/cards/the-hanged-man.jpg","description":"Người treo ngược nhưng thanh thản.","detailed_meaning":"Hy sinh và thay đổi góc nhìn.","upright":["Hy sinh","Buông bỏ","Góc nhìn mới","Sự trì hoãn"],"reversed":["Bế tắc","Sợ hãi hy sinh","Sự cứng nhắc"],"keywords":["Perspective","Release","Surrender"],"element":"Water","zodiac":"Neptune","yes_no":"maybe","slug":"the-hanged-man"},
{"name":"Death","number":13,"arcana":"major","suit":null,"image":"/images/cards/death.jpg","description":"Bộ xương cưỡi ngựa trắng.","detailed_meaning":"Sự biến đổi sâu sắc.","upright":["Kết thúc","Biến đổi","Chuyển giao","Cắt đứt"],"reversed":["Trì hoãn","Sợ hãi thay đổi","Sự trì trệ"],"keywords":["Endings","Change","Transition"],"element":"Water","zodiac":"Scorpio","yes_no":"no","slug":"death"},
{"name":"Temperance","number":14,"arcana":"major","suit":null,"image":"/images/cards/temperance.jpg","description":"Thiên thần rót nước giữa hai bình.","detailed_meaning":"Cân bằng là bí quyết.","upright":["Cân bằng","Điều độ","Kiên nhẫn","Hòa hợp"],"reversed":["Mất cân bằng","Thái quá","Sự vội vàng"],"keywords":["Balance","Patience","Moderation"],"element":"Fire","zodiac":"Sagittarius","yes_no":"yes","slug":"temperance"},
{"name":"The Devil","number":15,"arcana":"major","suit":null,"image":"/images/cards/the-devil.jpg","description":"Hình hài quỷ dữ xiềng xích hai con người.","detailed_meaning":"Xiềng xích do chính mình tạo ra.","upright":["Sự lệ thuộc","Bóng tối nội tâm","Vật chất","Cám dỗ"],"reversed":["Giải phóng","Tự do","Nhận thức","Buông bỏ"],"keywords":["Shadow self","Attachment","Addiction"],"element":"Earth","zodiac":"Capricorn","yes_no":"no","slug":"the-devil"},
{"name":"The Tower","number":16,"arcana":"major","suit":null,"image":"/images/cards/the-tower.jpg","description":"Tia sét đánh sập tòa tháp.","detailed_meaning":"Thay đổi đột ngột.","upright":["Sụp đổ","Thay đổi đột ngột","Sự thật","Khủng hoảng"],"reversed":["Tránh được tai họa","Nỗi sợ thay đổi","Trì hoãn"],"keywords":["Upheaval","Revelation","Disaster"],"element":"Fire","zodiac":"Mars","yes_no":"no","slug":"the-tower"},
{"name":"The Star","number":17,"arcana":"major","suit":null,"image":"/images/cards/the-star.jpg","description":"Người phụ nữ rót nước dưới bầu trời sao.","detailed_meaning":"Hy vọng và chữa lành.","upright":["Hy vọng","Chữa lành","Cảm hứng","Niềm tin"],"reversed":["Mất phương hướng","Tuyệt vọng","Thiếu cảm hứng"],"keywords":["Hope","Purpose","Renewal"],"element":"Air","zodiac":"Aquarius","yes_no":"yes","slug":"the-star"},
{"name":"The Moon","number":18,"arcana":"major","suit":null,"image":"/images/cards/the-moon.jpg","description":"Ánh trăng mờ ảo giữa hai tòa tháp.","detailed_meaning":"Ảo giác, nỗi sợ và trực giác.","upright":["Ảo giác","Nỗi sợ","Trực giác","Sự nhầm lẫn"],"reversed":["Sự thật phơi bày","Vượt qua nỗi sợ","Giải tỏa"],"keywords":["Illusion","Fear","Anxiety"],"element":"Water","zodiac":"Pisces","yes_no":"maybe","slug":"the-moon"},
{"name":"The Sun","number":19,"arcana":"major","suit":null,"image":"/images/cards/the-sun.jpg","description":"Đứa trẻ cưỡi ngựa trắng dưới ánh nắng.","detailed_meaning":"Lá bài tích cực nhất!","upright":["Thành công","Vui vẻ","Sức sống","Tự tin"],"reversed":["Thất vọng tạm thời","Khoe khoang","Thiếu lạc quan"],"keywords":["Joy","Success","Vitality"],"element":"Fire","zodiac":"Sun","yes_no":"yes","slug":"the-sun"},
{"name":"Judgement","number":20,"arcana":"major","suit":null,"image":"/images/cards/judgement.jpg","description":"Tiếng kèn thiên thần thức tỉnh linh hồn.","detailed_meaning":"Thức tỉnh và tự đánh giá lại.","upright":["Thức tỉnh","Tái sinh","Sự phán xét","Tiếng gọi"],"reversed":["Sự nghi ngờ","Trì hoãn quyết định","Chưa sẵn sàng"],"keywords":["Awakening","Renewal","Purpose"],"element":"Fire","zodiac":"Pluto","yes_no":"yes","slug":"judgement"},
{"name":"The World","number":21,"arcana":"major","suit":null,"image":"/images/cards/the-world.jpg","description":"Vũ công trong vòng hoa nguyệt quế.","detailed_meaning":"Sự trọn vẹn và hoàn tất.","upright":["Hoàn tất","Thành tựu","Du lịch","Sự trọn vẹn"],"reversed":["Chưa hoàn thiện","Thiếu tổng thể","Sự trì trệ"],"keywords":["Completion","Integration","Travel"],"element":"Earth","zodiac":"Saturn","yes_no":"yes","slug":"the-world"},
{"name":"Ace of Wands","number":1,"arcana":"minor","suit":"wands","image":"/images/cards/ace-of-wands.jpg","description":"Bàn tay cầm chiếc gậy đang đâm chồi.","detailed_meaning":"Ngọn lửa sáng tạo bùng cháy.","upright":["Cảm hứng","Cơ hội mới","Nhiệt huyết","Sáng tạo"],"reversed":["Thiếu động lực","Sự trì hoãn","Mất phương hướng"],"keywords":["Inspiration","New opportunity","Growth"],"element":"Fire","zodiac":null,"yes_no":"yes","slug":"ace-of-wands"},
{"name":"Two of Wands","number":2,"arcana":"minor","suit":"wands","image":"/images/cards/two-of-wands.jpg","description":"Người đàn ông cầm quả địa cầu nhìn xa.","detailed_meaning":"Lập kế hoạch cho tương lai.","upright":["Lập kế hoạch","Quyết định","Khám phá","Tầm nhìn"],"reversed":["Sợ hãi tương lai","Thiếu chuẩn bị","Sự do dự"],"keywords":["Planning","Decisions","Discovery"],"element":"Fire","zodiac":"Mars in Aries","yes_no":"maybe","slug":"two-of-wands"},
{"name":"Three of Wands","number":3,"arcana":"minor","suit":"wands","image":"/images/cards/three-of-wands.jpg","description":"Nhìn những con thuyền rời bến.","detailed_meaning":"Nỗ lực bắt đầu mang lại kết quả.","upright":["Mở rộng","Tiến triển","Tầm nhìn xa","Hợp tác"],"reversed":["Sự chậm trễ","Thất vọng","Thiếu tầm nhìn"],"keywords":["Expansion","Progress","Foresight"],"element":"Fire","zodiac":"Sun in Aries","yes_no":"yes","slug":"three-of-wands"},
{"name":"Four of Wands","number":4,"arcana":"minor","suit":"wands","image":"/images/cards/four-of-wands.jpg","description":"Hai người nhảy múa dưới vòng hoa.","detailed_meaning":"Ăn mừng và ổn định.","upright":["Ăn mừng","Hòa hợp","Thư giãn","Hạnh phúc","Sự ổn định"],"reversed":["Thiếu hòa hợp","Mâu thuẫn gia đình"],"keywords":["Celebration","Harmony","Home"],"element":"Fire","zodiac":"Venus in Aries","yes_no":"yes","slug":"four-of-wands"},
{"name":"Five of Wands","number":5,"arcana":"minor","suit":"wands","image":"/images/cards/five-of-wands.jpg","description":"Năm thanh niên cầm gậy tranh đấu.","detailed_meaning":"Cạnh tranh và xung đột nhỏ.","upright":["Cạnh tranh","Xung đột","Bất đồng","Sự hỗn loạn"],"reversed":["Tránh né xung đột","Hợp tác","Giải quyết mâu thuẫn"],"keywords":["Competition","Conflict","Disagreement"],"element":"Fire","zodiac":"Saturn in Leo","yes_no":"no","slug":"five-of-wands"},
{"name":"Six of Wands","number":6,"arcana":"minor","suit":"wands","image":"/images/cards/six-of-wands.jpg","description":"Kỵ sĩ cưỡi ngựa trắng đeo vòng nguyệt quế.","detailed_meaning":"Công nhận và niềm tự hào.","upright":["Chiến thắng","Công nhận","Tự hào","Tiến bộ"],"reversed":["Thất bại","Thiếu tự tin","Mất uy tín"],"keywords":["Success","Public recognition","Victory"],"element":"Fire","zodiac":"Jupiter in Leo","yes_no":"yes","slug":"six-of-wands"},
{"name":"Seven of Wands","number":7,"arcana":"minor","suit":"wands","image":"/images/cards/seven-of-wands.jpg","description":"Đứng trên đỉnh đồi chống lại 6 gậy.","detailed_meaning":"Bảo vệ quan điểm và kiên trì.","upright":["Bảo vệ","Kiên trì","Thử thách","Lòng dũng cảm"],"reversed":["Bỏ cuộc","Bị áp đảo","Thiếu tự tin"],"keywords":["Defense","Perseverance","Challenge"],"element":"Fire","zodiac":"Mars in Leo","yes_no":"yes","slug":"seven-of-wands"},
{"name":"Eight of Wands","number":8,"arcana":"minor","suit":"wands","image":"/images/cards/eight-of-wands.jpg","description":"Tám gậy bay vút trên không.","detailed_meaning":"Tốc độ và chuyển động nhanh.","upright":["Tốc độ","Tin tức","Hành động nhanh","Sự tiến triển"],"reversed":["Chậm trễ","Hấp tấp","Sự hỗn loạn"],"keywords":["Speed","Action","Movement"],"element":"Fire","zodiac":"Mercury in Sagittarius","yes_no":"yes","slug":"eight-of-wands"},
{"name":"Nine of Wands","number":9,"arcana":"minor","suit":"wands","image":"/images/cards/nine-of-wands.jpg","description":"Người bị thương canh gác.","detailed_meaning":"Kiên cường, sắp về đích.","upright":["Kiên cường","Cảnh giác","Sức bền","Sắp về đích"],"reversed":["Kiệt sức","Rút lui","Mất cảnh giác"],"keywords":["Resilience","Persistence","Last stand"],"element":"Fire","zodiac":"Moon in Sagittarius","yes_no":"yes","slug":"nine-of-wands"},
{"name":"Ten of Wands","number":10,"arcana":"minor","suit":"wands","image":"/images/cards/ten-of-wands.jpg","description":"Mang vác mười chiếc gậy.","detailed_meaning":"Gánh nặng và quá tải.","upright":["Gánh nặng","Trách nhiệm","Quá tải","Làm việc quá sức"],"reversed":["Buông bỏ gánh nặng","Sụp đổ","Tránh né"],"keywords":["Burden","Responsibility","Struggle"],"element":"Fire","zodiac":"Saturn in Sagittarius","yes_no":"no","slug":"ten-of-wands"},
{"name":"Page of Wands","number":11,"arcana":"minor","suit":"wands","image":"/images/cards/page-of-wands.jpg","description":"Thiếu niên nhìn chiếc gậy đầy nhiệt huyết.","detailed_meaning":"Khám phá và khởi đầu cảm hứng.","upright":["Khám phá","Nhiệt huyết","Tin vui","Sự ngây thơ"],"reversed":["Thiếu định hướng","Tin xấu","Thiếu kiên nhẫn"],"keywords":["Exploration","Enthusiasm","Discovery"],"element":"Fire","zodiac":null,"yes_no":"yes","slug":"page-of-wands"},
{"name":"Knight of Wands","number":12,"arcana":"minor","suit":"wands","image":"/images/cards/knight-of-wands.jpg","description":"Hiệp sĩ cưỡi ngựa đầy năng lượng.","detailed_meaning":"Đam mê và hành động quyết đoán.","upright":["Năng lượng","Đam mê","Hành động","Mạo hiểm"],"reversed":["Hấp tấp","Hung hăng","Mất kiểm soát"],"keywords":["Energy","Passion","Adventure"],"element":"Fire","zodiac":null,"yes_no":"yes","slug":"knight-of-wands"},
{"name":"Queen of Wands","number":13,"arcana":"minor","suit":"wands","image":"/images/cards/queen-of-wands.jpg","description":"Hoàng hậu quyền uy cầm gậy và hướng dương.","detailed_meaning":"Tự tin và sức hút mãnh liệt.","upright":["Tự tin","Độc lập","Quyến rũ","Năng lượng"],"reversed":["Ích kỷ","Đố kỵ","Thiếu tự tin"],"keywords":["Confidence","Independence","Social butterfly"],"element":"Fire","zodiac":null,"yes_no":"yes","slug":"queen-of-wands"},
{"name":"King of Wands","number":14,"arcana":"minor","suit":"wands","image":"/images/cards/king-of-wands.jpg","description":"Vị vua uy nghiêm trên ngai vàng hình rồng.","detailed_meaning":"Thủ lĩnh bẩm sinh với tầm nhìn xa.","upright":["Lãnh đạo","Tầm nhìn","Bản lĩnh","Sáng tạo","Sự bảo vệ"],"reversed":["Độc đoán","Kiêu ngạo","Thiếu kiên nhẫn"],"keywords":["Leadership","Vision","Honor"],"element":"Fire","zodiac":null,"yes_no":"yes","slug":"king-of-wands"},
{"name":"Ace of Cups","number":1,"arcana":"minor","suit":"cups","image":"/images/cards/ace-of-cups.jpg","description":"Bàn tay nâng chiếc cốc tràn đầy nước.","detailed_meaning":"Khởi đầu cảm xúc mới.","upright":["Tình yêu mới","Hạnh phúc","Trực giác","Sáng tạo","Sự trào dâng"],"reversed":["Cảm xúc bị kìm nén","Thất tình","Sự trống rỗng"],"keywords":["Love","New feelings","Spirituality"],"element":"Water","zodiac":null,"yes_no":"yes","slug":"ace-of-cups"},
{"name":"Two of Cups","number":2,"arcana":"minor","suit":"cups","image":"/images/cards/two-of-cups.jpg","description":"Nam nữ trao nhau cốc.","detailed_meaning":"Kết nối sâu sắc giữa hai linh hồn.","upright":["Kết nối","Tình yêu","Hợp tác","Hòa hợp","Sự thấu hiểu"],"reversed":["Chia rẽ","Mất cân bằng","Xung đột"],"keywords":["Partnership","Attraction","Unity"],"element":"Water","zodiac":"Venus in Cancer","yes_no":"yes","slug":"two-of-cups"},
{"name":"Three of Cups","number":3,"arcana":"minor","suit":"cups","image":"/images/cards/three-of-cups.jpg","description":"Ba người phụ nữ nâng ly chúc mừng.","detailed_meaning":"Tình bạn và chia sẻ niềm vui.","upright":["Tình bạn","Ăn mừng","Cộng đồng","Hỗ trợ","Niềm vui"],"reversed":["Sự cô lập","Tiệc tùng quá đà","Bất hòa"],"keywords":["Friendship","Community","Celebration"],"element":"Water","zodiac":"Mercury in Cancer","yes_no":"yes","slug":"three-of-cups"},
{"name":"Four of Cups","number":4,"arcana":"minor","suit":"cups","image":"/images/cards/four-of-cups.jpg","description":"Thanh niên thờ ơ dưới gốc cây.","detailed_meaning":"Chán chường và bỏ lỡ cơ hội.","upright":["Thờ ơ","Chán nản","Trầm tư","Bỏ lỡ cơ hội"],"reversed":["Thức tỉnh","Sẵn sàng","Hứng khởi trở lại"],"keywords":["Apathy","Contemplation","Withdrawal"],"element":"Water","zodiac":"Moon in Cancer","yes_no":"maybe","slug":"four-of-cups"},
{"name":"Five of Cups","number":5,"arcana":"minor","suit":"cups","image":"/images/cards/five-of-cups.jpg","description":"Người trùm áo choàng đen trước ba cốc đổ.","detailed_meaning":"Nỗi đau và mất mát, nhưng vẫn còn hy vọng.","upright":["Hối tiếc","Mất mát","Đau buồn","Thất vọng"],"reversed":["Chấp nhận","Vượt qua đau khổ","Lạc quan"],"keywords":["Loss","Regret","Grief"],"element":"Water","zodiac":"Mars in Scorpio","yes_no":"no","slug":"five-of-cups"},
{"name":"Six of Cups","number":6,"arcana":"minor","suit":"cups","image":"/images/cards/six-of-cups.jpg","description":"Cậu bé trao cốc hoa cho cô bé.","detailed_meaning":"Hoài niệm và lòng tốt thuần khiết.","upright":["Hoài niệm","Ngây thơ","Quá khứ","Sự tử tế","Gia đình"],"reversed":["Mắc kẹt quá khứ","Trưởng thành gượng ép"],"keywords":["Nostalgia","Innocence","Reunion"],"element":"Water","zodiac":"Sun in Scorpio","yes_no":"yes","slug":"six-of-cups"},
{"name":"Seven of Cups","number":7,"arcana":"minor","suit":"cups","image":"/images/cards/seven-of-cups.jpg","description":"Bảy cốc lơ lửng trong đám mây.","detailed_meaning":"Quá nhiều lựa chọn và ảo tưởng.","upright":["Ảo tưởng","Lựa chọn","Ước mơ","Sự nhầm lẫn"],"reversed":["Quyết đoán","Hiện thực hóa","Phá tan ảo mộng"],"keywords":["Searching for purpose","Choices","Illusion"],"element":"Water","zodiac":"Venus in Scorpio","yes_no":"maybe","slug":"seven-of-cups"},
{"name":"Eight of Cups","number":8,"arcana":"minor","suit":"cups","image":"/images/cards/eight-of-cups.jpg","description":"Quay lưng bước đi vào ban đêm.","detailed_meaning":"Dứt áo ra đi tìm kiếm điều sâu sắc hơn.","upright":["Rời bỏ","Tìm kiếm chân lý","Buông bỏ","Thay đổi tâm hồn"],"reversed":["Sợ hãi ra đi","Dùng dằng","Trì hoãn"],"keywords":["Abandonment","Withdrawal","Escapism"],"element":"Water","zodiac":"Saturn in Pisces","yes_no":"no","slug":"eight-of-cups"},
{"name":"Nine of Cups","number":9,"arcana":"minor","suit":"cups","image":"/images/cards/nine-of-cups.jpg","description":"Người mỉm cười trước chín cốc.","detailed_meaning":"Ước gì được nấy, mãn nguyện.","upright":["Mãn nguyện","Ước mơ thành sự thật","Hạnh phúc","Thịnh vượng"],"reversed":["Chưa hài lòng","Khoe khoang","Tham lam"],"keywords":["Contentment","Satisfaction","Wishes fulfilled"],"element":"Water","zodiac":"Jupiter in Pisces","yes_no":"yes","slug":"nine-of-cups"},
{"name":"Ten of Cups","number":10,"arcana":"minor","suit":"cups","image":"/images/cards/ten-of-cups.jpg","description":"Cặp vợ chồng hạnh phúc dưới cầu vồng.","detailed_meaning":"Viên mãn tột độ trong tình cảm.","upright":["Hạnh phúc gia đình","Hòa hợp","Viên mãn","Bình yên","Sự kết nối"],"reversed":["Mâu thuẫn gia đình","Tan vỡ","Sự xa cách"],"keywords":["Divine love","Bliss","Alignment"],"element":"Water","zodiac":"Mars in Pisces","yes_no":"yes","slug":"ten-of-cups"},
{"name":"Page of Cups","number":11,"arcana":"minor","suit":"cups","image":"/images/cards/page-of-cups.jpg","description":"Thanh niên cầm cốc có cá thò đầu.","detailed_meaning":"Thông điệp bất ngờ về tình cảm.","upright":["Tin vui tình cảm","Sáng tạo","Trực giác","Sự nhạy cảm"],"reversed":["Sự trẻ con","Cảm xúc thất thường","Mơ mộng hão huyền"],"keywords":["Creative opportunity","Intuition","Curiosity"],"element":"Water","zodiac":null,"yes_no":"yes","slug":"page-of-cups"},
{"name":"Knight of Cups","number":12,"arcana":"minor","suit":"cups","image":"/images/cards/knight-of-cups.jpg","description":"Hiệp sĩ cưỡi ngựa trắng nâng cốc.","detailed_meaning":"Sứ giả của tình yêu và lãng mạn.","upright":["Lãng mạn","Lời mời","Cảm hứng","Người đưa tin"],"reversed":["Thiếu thực tế","Thay lòng đổi dạ","Ảo tưởng"],"keywords":["Romance","Charm","Idealism"],"element":"Water","zodiac":null,"yes_no":"yes","slug":"knight-of-cups"},
{"name":"Queen of Cups","number":13,"arcana":"minor","suit":"cups","image":"/images/cards/queen-of-cups.jpg","description":"Hoàng hậu xinh đẹp bên bờ biển.","detailed_meaning":"Trực giác và lòng trắc ẩn.","upright":["Thấu cảm","Trực giác","Lòng tốt","Sự dịu dàng"],"reversed":["Cảm xúc thái quá","Sự phụ thuộc","Mất kết nối"],"keywords":["Compassion","Calm","Intuitive"],"element":"Water","zodiac":null,"yes_no":"yes","slug":"queen-of-cups"},
{"name":"King of Cups","number":14,"arcana":"minor","suit":"cups","image":"/images/cards/king-of-cups.jpg","description":"Vị vua giữa biển cả mênh mông.","detailed_meaning":"Trưởng thành về cảm xúc.","upright":["Điềm tĩnh","Trưởng thành","Bao dung","Kiểm soát cảm xúc"],"reversed":["Thao túng","Lạnh lùng","Mất cân bằng"],"keywords":["Emotional balance","Generosity","Control"],"element":"Water","zodiac":null,"yes_no":"yes","slug":"king-of-cups"},
{"name":"Ace of Swords","number":1,"arcana":"minor","suit":"swords","image":"/images/cards/ace-of-swords.jpg","description":"Bàn tay cầm thanh kiếm xuyên vương miện.","detailed_meaning":"Thức tỉnh lý trí và sức mạnh sự thật.","upright":["Sự thật","Rõ ràng","Quyết đoán","Thành công trí tuệ"],"reversed":["Nhầm lẫn","Thiếu khách quan","Thất bại"],"keywords":["Breakthrough","Clarity","Sharp mind"],"element":"Air","zodiac":null,"yes_no":"yes","slug":"ace-of-swords"},
{"name":"Two of Swords","number":2,"arcana":"minor","suit":"swords","image":"/images/cards/two-of-swords.jpg","description":"Người phụ nữ bịt mắt bắt chéo hai kiếm.","detailed_meaning":"Bế tắc và trốn tránh sự thật.","upright":["Lưỡng lự","Bế tắc","Tránh né","Cân bằng mong manh"],"reversed":["Quyết định","Nhìn ra sự thật","Sự hỗn loạn"],"keywords":["Difficult choices","Stalemate","Denial"],"element":"Air","zodiac":"Moon in Libra","yes_no":"maybe","slug":"two-of-swords"},
{"name":"Three of Swords","number":3,"arcana":"minor","suit":"swords","image":"/images/cards/three-of-swords.jpg","description":"Trái tim bị đâm bởi ba thanh kiếm.","detailed_meaning":"Nỗi đau và tổn thương tinh thần.","upright":["Đau lòng","Chia tay","Sự phản bội","Nỗi buồn"],"reversed":["Hồi phục","Tha thứ","Giải phóng nỗi đau"],"keywords":["Heartbreak","Sorrow","Grief"],"element":"Air","zodiac":"Saturn in Libra","yes_no":"no","slug":"three-of-swords"},
{"name":"Four of Swords","number":4,"arcana":"minor","suit":"swords","image":"/images/cards/four-of-swords.jpg","description":"Hiệp sĩ nằm nghỉ trên hầm mộ.","detailed_meaning":"Cần nghỉ ngơi và hồi phục.","upright":["Nghỉ ngơi","Hồi phục","Tĩnh tâm","Sự suy ngẫm"],"reversed":["Kiệt sức","Trở lại quá sớm","Sự bồn chồn"],"keywords":["Rest","Recovery","Meditation"],"element":"Air","zodiac":"Jupiter in Libra","yes_no":"maybe","slug":"four-of-swords"},
{"name":"Five of Swords","number":5,"arcana":"minor","suit":"swords","image":"/images/cards/five-of-swords.jpg","description":"Người cầm ba kiếm mỉm cười đắc thắng.","detailed_meaning":"Chiến thắng bằng mọi giá nhưng cay đắng.","upright":["Xung đột","Thắng lợi cay đắng","Sự ích kỷ","Bất hòa"],"reversed":["Hòa giải","Hối hận","Kết thúc cuộc chiến"],"keywords":["Conflict","Winning at all costs","Betrayal"],"element":"Air","zodiac":"Venus in Aquarius","yes_no":"no","slug":"five-of-swords"},
{"name":"Six of Swords","number":6,"arcana":"minor","suit":"swords","image":"/images/cards/six-of-swords.jpg","description":"Chèo thuyền đi về phía bờ bình yên.","detailed_meaning":"Rời bỏ rắc rối để hồi phục.","upright":["Chuyển tiếp","Rời bỏ rắc rối","Hồi phục","Hành trình","Sự hỗ trợ"],"reversed":["Mắc kẹt","Quá khứ bám đuổi","Trì hoãn"],"keywords":["Transition","Moving on","Departure"],"element":"Air","zodiac":"Mercury in Aquarius","yes_no":"yes","slug":"six-of-swords"},
{"name":"Seven of Swords","number":7,"arcana":"minor","suit":"swords","image":"/images/cards/seven-of-swords.jpg","description":"Người lén lút ôm năm thanh kiếm.","detailed_meaning":"Chiến thuật và bí mật.","upright":["Chiến thuật","Bí mật","Sự khôn ngoan","Độc lập"],"reversed":["Sự thật lộ diện","Hối hận","Lời khuyên đúng"],"keywords":["Strategy","Deception","Stealth"],"element":"Air","zodiac":"Moon in Aquarius","yes_no":"no","slug":"seven-of-swords"},
{"name":"Eight of Swords","number":8,"arcana":"minor","suit":"swords","image":"/images/cards/eight-of-swords.jpg","description":"Người bị bịt mắt và trói lỏng giữa tám kiếm.","detailed_meaning":"Cảm giác mắc kẹt nhưng thực ra tự do.","upright":["Bế tắc","Bị giới hạn","Nỗi sợ hãi","Nạn nhân"],"reversed":["Giải thoát","Tự lực","Nhìn ra sự thật"],"keywords":["Imprisonment","Self-victimization","Limitation"],"element":"Air","zodiac":"Jupiter in Gemini","yes_no":"no","slug":"eight-of-swords"},
{"name":"Nine of Swords","number":9,"arcana":"minor","suit":"swords","image":"/images/cards/nine-of-swords.jpg","description":"Người ngồi bật dậy trên giường đau khổ.","detailed_meaning":"Ác mộng và lo âu tột độ.","upright":["Lo âu","Mất ngủ","Ác mộng","Sự suy sụp"],"reversed":["Giải tỏa căng thẳng","Hy vọng","Vượt qua nỗi sợ"],"keywords":["Anxiety","Worry","Fear"],"element":"Air","zodiac":"Mars in Gemini","yes_no":"no","slug":"nine-of-swords"},
{"name":"Ten of Swords","number":10,"arcana":"minor","suit":"swords","image":"/images/cards/ten-of-swords.jpg","description":"Nằm gục với mười kiếm đâm vào lưng.","detailed_meaning":"Kết thúc đau đớn nhưng ánh sáng đang đến.","upright":["Thất bại","Sự phản bội","Kết thúc đau đớn","Chạm đáy"],"reversed":["Hồi phục","Vượt qua nghịch cảnh","Sự tái sinh"],"keywords":["Betrayal","Finality","Rock bottom"],"element":"Air","zodiac":"Sun in Gemini","yes_no":"no","slug":"ten-of-swords"},
{"name":"Page of Swords","number":11,"arcana":"minor","suit":"swords","image":"/images/cards/page-of-swords.jpg","description":"Thanh niên trên ngọn đồi lộng gió.","detailed_meaning":"Trí tò mò và nhạy bén.","upright":["Tò mò","Nhạy bén","Tin tức","Sự thật","Năng lượng tinh thần"],"reversed":["Thị phi","Thiếu thực tế","Nói suông"],"keywords":["Curiosity","Mental energy","Communication"],"element":"Air","zodiac":null,"yes_no":"yes","slug":"page-of-swords"},
{"name":"Knight of Swords","number":12,"arcana":"minor","suit":"swords","image":"/images/cards/knight-of-swords.jpg","description":"Hiệp sĩ cưỡi ngựa lao đi.","detailed_meaning":"Tốc độ, quyết đoán và đôi khi liều lĩnh.","upright":["Quyết đoán","Tham vọng","Hành động nhanh","Sự sắc sảo"],"reversed":["Hung hăng","Mất kiểm soát","Sự hấp tấp"],"keywords":["Ambitious","Driven","Fast-thinking"],"element":"Air","zodiac":null,"yes_no":"yes","slug":"knight-of-swords"},
{"name":"Queen of Swords","number":13,"arcana":"minor","suit":"swords","image":"/images/cards/queen-of-swords.jpg","description":"Hoàng hậu nghiêm nghị cầm kiếm.","detailed_meaning":"Độc lập, khách quan và trí tuệ sắc sảo.","upright":["Độc lập","Khách quan","Trực ngôn","Trí tuệ"],"reversed":["Cay nghiệt","Lạnh lùng","Thao túng"],"keywords":["Complexity","Perceptive","Clear boundaries"],"element":"Air","zodiac":null,"yes_no":"yes","slug":"queen-of-swords"},
{"name":"King of Swords","number":14,"arcana":"minor","suit":"swords","image":"/images/cards/king-of-swords.jpg","description":"Vị vua cầm thanh kiếm quyền lực.","detailed_meaning":"Đỉnh cao quyền lực trí tuệ và đạo đức.","upright":["Quyền lực","Kỷ luật","Lý trí","Công minh"],"reversed":["Chuyên quyền","Tàn nhẫn","Lạm dụng trí tuệ"],"keywords":["Intellectual power","Authority","Truth"],"element":"Air","zodiac":null,"yes_no":"yes","slug":"king-of-swords"},
{"name":"Ace of Pentacles","number":1,"arcana":"minor","suit":"pentacles","image":"/images/cards/ace-of-pentacles.jpg","description":"Bàn tay nâng đồng tiền vàng trên vườn xanh.","detailed_meaning":"Khởi đầu mới về vật chất.","upright":["Cơ hội tài chính","Thịnh vượng","Hiện thực hóa","Sức khỏe"],"reversed":["Bỏ lỡ cơ hội","Mất mát tài chính","Thiếu thực tế"],"keywords":["New resource","Prosperity","Manifestation"],"element":"Earth","zodiac":null,"yes_no":"yes","slug":"ace-of-pentacles"},
{"name":"Two of Pentacles","number":2,"arcana":"minor","suit":"pentacles","image":"/images/cards/two-of-pentacles.jpg","description":"Thanh niên tung hứng hai đồng tiền.","detailed_meaning":"Cân bằng giữa các ưu tiên.","upright":["Cân bằng","Linh hoạt","Ưu tiên","Xoay xở"],"reversed":["Mất cân bằng","Quá tải","Hỗn loạn"],"keywords":["Balance","Adaptability","Priorities"],"element":"Earth","zodiac":"Jupiter in Capricorn","yes_no":"maybe","slug":"two-of-pentacles"},
{"name":"Three of Pentacles","number":3,"arcana":"minor","suit":"pentacles","image":"/images/cards/three-of-pentacles.jpg","description":"Thợ chạm khắc thảo luận bản vẽ.","detailed_meaning":"Hợp tác và kỹ năng chuyên môn.","upright":["Hợp tác","Kỹ năng","Học hỏi","Xây dựng","Làm việc nhóm"],"reversed":["Thiếu kỹ năng","Bất đồng","Kém hiệu quả"],"keywords":["Teamwork","Collaboration","Learning"],"element":"Earth","zodiac":"Mars in Capricorn","yes_no":"yes","slug":"three-of-pentacles"},
{"name":"Four of Pentacles","number":4,"arcana":"minor","suit":"pentacles","image":"/images/cards/four-of-pentacles.jpg","description":"Người ôm chặt đồng tiền.","detailed_meaning":"Bảo thủ và nhu cầu an toàn quá mức.","upright":["Bảo vệ","Tiết kiệm","Sự ổn định","Chiếm hữu"],"reversed":["Tham lam","Cứng nhắc","Lãng phí","Buông bỏ"],"keywords":["Conservation","Scarcity","Security"],"element":"Earth","zodiac":"Sun in Capricorn","yes_no":"maybe","slug":"four-of-pentacles"},
{"name":"Five of Pentacles","number":5,"arcana":"minor","suit":"pentacles","image":"/images/cards/five-of-pentacles.jpg","description":"Hai người nghèo qua khung cửa nhà thờ.","detailed_meaning":"Mất mát tài chính hoặc cô đơn.","upright":["Nghèo khó","Mất mát","Sự cô lập","Khó khăn"],"reversed":["Hồi phục","Tìm thấy sự giúp đỡ","Kết thúc nghịch cảnh"],"keywords":["Hardship","Poverty","Isolation"],"element":"Earth","zodiac":"Mercury in Taurus","yes_no":"no","slug":"five-of-pentacles"},
{"name":"Six of Pentacles","number":6,"arcana":"minor","suit":"pentacles","image":"/images/cards/six-of-pentacles.jpg","description":"Người giàu ban phát tiền.","detailed_meaning":"Hào phóng và cân bằng cho-nhận.","upright":["Hào phóng","Từ thiện","Chia sẻ","Công bằng","Sự giúp đỡ"],"reversed":["Ích kỷ","Nợ nần","Lợi dụng"],"keywords":["Generosity","Charity","Sharing"],"element":"Earth","zodiac":"Moon in Taurus","yes_no":"yes","slug":"six-of-pentacles"},
{"name":"Seven of Pentacles","number":7,"arcana":"minor","suit":"pentacles","image":"/images/cards/seven-of-pentacles.jpg","description":"Nông dân nhìn ngắm thành quả.","detailed_meaning":"Kiên nhẫn và đánh giá lại.","upright":["Kiên nhẫn","Gặt hái","Đầu tư dài hạn","Đánh giá"],"reversed":["Nóng vội","Thất vọng","Thiếu tầm nhìn"],"keywords":["Investment","Patience","Assessment"],"element":"Earth","zodiac":"Saturn in Taurus","yes_no":"maybe","slug":"seven-of-pentacles"},
{"name":"Eight of Pentacles","number":8,"arcana":"minor","suit":"pentacles","image":"/images/cards/eight-of-pentacles.jpg","description":"Thợ thủ công đục đẽo tỉ mỉ.","detailed_meaning":"Tận tụy và làm chủ kỹ năng.","upright":["Chăm chỉ","Kỹ năng","Tận tâm","Học hỏi","Sự tập trung"],"reversed":["Lười biếng","Thiếu tập trung","Cẩu thả"],"keywords":["Mastery","Diligence","Skill"],"element":"Earth","zodiac":"Sun in Virgo","yes_no":"yes","slug":"eight-of-pentacles"},
{"name":"Nine of Pentacles","number":9,"arcana":"minor","suit":"pentacles","image":"/images/cards/nine-of-pentacles.jpg","description":"Người phụ nữ quý phái trong vườn nho.","detailed_meaning":"Tự chủ và tận hưởng thành quả.","upright":["Độc lập","Thành đạt","Hưởng thụ","Tự tin","Thịnh vượng"],"reversed":["Lãng phí","Sự phụ thuộc","Rủi ro tài chính"],"keywords":["Luxury","Independence","Self-sufficiency"],"element":"Earth","zodiac":"Venus in Virgo","yes_no":"yes","slug":"nine-of-pentacles"},
{"name":"Ten of Pentacles","number":10,"arcana":"minor","suit":"pentacles","image":"/images/cards/ten-of-pentacles.jpg","description":"Cụ già trong cung điện với gia đình.","detailed_meaning":"Thịnh vượng lâu bền và di sản.","upright":["Thịnh vượng","Di sản","Gia đình","Sự ổn định lâu dài"],"reversed":["Rắc rối tài chính","Mâu thuẫn gia đình","Mất di sản"],"keywords":["Wealth","Inheritance","Family tradition"],"element":"Earth","zodiac":"Mercury in Virgo","yes_no":"yes","slug":"ten-of-pentacles"},
{"name":"Page of Pentacles","number":11,"arcana":"minor","suit":"pentacles","image":"/images/cards/page-of-pentacles.jpg","description":"Thanh niên nâng niu đồng tiền vàng.","detailed_meaning":"Cơ hội mới để kiếm tiền.","upright":["Cơ hội mới","Học hỏi","Thực tế","Tin vui tài chính"],"reversed":["Thiếu định hướng","Lười biếng","Bỏ lỡ cơ hội"],"keywords":["Manifestation","Financial opportunity","Ambition"],"element":"Earth","zodiac":null,"yes_no":"yes","slug":"page-of-pentacles"},
{"name":"Knight of Pentacles","number":12,"arcana":"minor","suit":"pentacles","image":"/images/cards/knight-of-pentacles.jpg","description":"Hiệp sĩ cưỡi ngựa đen vững chãi.","detailed_meaning":"Chăm chỉ và thực tế nhất.","upright":["Chăm chỉ","Kiên trì","Thực tế","Trách nhiệm","Sự ổn định"],"reversed":["Bảo thủ","Lười biếng","Sự trì trệ"],"keywords":["Hard work","Productivity","Routine"],"element":"Earth","zodiac":null,"yes_no":"yes","slug":"knight-of-pentacles"},
{"name":"Queen of Pentacles","number":13,"arcana":"minor","suit":"pentacles","image":"/images/cards/queen-of-pentacles.jpg","description":"Hoàng hậu hiền từ giữa thiên nhiên.","detailed_meaning":"Quản lý tài chính tốt và nuôi dưỡng.","upright":["Nuôi dưỡng","Thịnh vượng","Thực tế","Hào phóng","Sự an tâm"],"reversed":["Mất cân bằng","Ích kỷ","Lo lắng tài chính"],"keywords":["Nurturing","Practicality","Financial security"],"element":"Earth","zodiac":null,"yes_no":"yes","slug":"queen-of-pentacles"},
{"name":"King of Pentacles","number":14,"arcana":"minor","suit":"pentacles","image":"/images/cards/king-of-pentacles.jpg","description":"Vị vua giữa hoa trái sung túc.","detailed_meaning":"Đỉnh cao thành công vật chất.","upright":["Thành công","Thịnh vượng","Kỷ luật","Bản lĩnh","Sự giàu có"],"reversed":["Tham lam","Độc đoán","Rủi ro tài chính"],"keywords":["Wealth","Abundance","Business"],"element":"Earth","zodiac":null,"yes_no":"yes","slug":"king-of-pentacles"}
];

async function seed() {
  await client.connect();
  console.log('🌱 Inserting ' + cards.length + ' cards...\n');

  // Delete existing
  await client.query('DELETE FROM "Card"');
  console.log('  🗑️ Deleted existing cards');

  // Insert each card
  let ok = 0;
  for (const c of cards) {
    await client.query(
      `INSERT INTO "Card" (name, number, arcana, suit, image, description, detailed_meaning, upright, reversed, keywords, element, zodiac, yes_no, slug)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,
      [c.name, c.number, c.arcana, c.suit, c.image, c.description, c.detailed_meaning, c.upright, c.reversed, c.keywords, c.element, c.zodiac, c.yes_no, c.slug]
    );
    ok++;
  }
  console.log('  ✅ Inserted ' + ok + '/' + cards.length);

  // Verify
  const res = await client.query('SELECT COUNT(*) FROM "Card"');
  console.log('\n🎴 Done! Total in DB: ' + res.rows[0].count);

  await client.end();
}

seed().catch(e => { console.error(e); process.exit(1); });
